import { makeStyles } from "@mui/styles";

const useStyles = (themeData) =>
  makeStyles(() => ({
    container: {
      padding: "90px 0px",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: themeData.surfaceAlt,
      "@media (max-width:768px)": {
        padding: "48px 0px",
      },
    },
    card: {
      position: "relative",
      overflow: "hidden",
      backgroundColor: `${themeData.glassBg} !important`,
      backdropFilter: "blur(14px)",
      WebkitBackdropFilter: "blur(14px)",
      color: `${themeData.text} !important`,
      border: `1px solid ${themeData.glassBorder}`,
      height: "100%",
      width: "100%",
      boxSizing: "border-box",
      display: "flex !important",
      flexDirection: "column",
      justifyContent: "space-between",
      boxShadow: `${themeData.shadow} !important`,
      borderRadius: "16px !important",
      transformStyle: "preserve-3d",
      willChange: "transform",
      transition: "transform 300ms ease, box-shadow 300ms ease, border-color 300ms ease !important",
      "&::before": {
        content: '""',
        position: "absolute",
        inset: 0,
        borderRadius: "inherit",
        background: `radial-gradient(280px circle at var(--mx, 50%) var(--my, 0%), ${themeData.glow}, transparent 70%)`,
        opacity: 0,
        transition: "opacity 300ms ease",
        pointerEvents: "none",
        zIndex: 2,
      },
      "&:hover::before": {
        opacity: 1,
      },
      "& .MuiCardContent-root, & .MuiCardActions-root": {
        position: "relative",
        zIndex: 3,
      },
      "&:hover": {
        transform: "translateY(-8px)",
        borderColor: themeData.accent,
        boxShadow: `0px 20px 40px -12px ${themeData.glow} !important`,
        "& $image": {
          transform: "scale(1.06)",
        },
      },
    },
    imageWrapper: {
      position: "relative",
      width: "100%",
      height: "clamp(170px, 42vw, 200px)",
      overflow: "hidden",
      backgroundColor: themeData.background,
      borderBottom: `1px solid ${themeData.glassBorder}`,
    },
    image: {
      width: "100%",
      height: "100%",
      objectFit: "cover",
      transition: "transform 0.5s cubic-bezier(0.2, 0.8, 0.2, 1)",
      display: "block",
    },
    badge: {
      position: "absolute",
      top: 12,
      right: 12,
      backgroundColor: `${themeData.primary} !important`,
      color: `${themeData.white} !important`,
      fontWeight: "700 !important",
      fontSize: "11px !important",
      letterSpacing: "0.5px",
      borderRadius: "6px !important",
      backdropFilter: "blur(8px)",
      boxShadow: "0 2px 8px rgba(0,0,0,0.3)",
      zIndex: 4,
    },
    chipRow: {
      display: "flex",
      flexWrap: "wrap",
      gap: 6,
      marginTop: 14,
    },
    chip: {
      backgroundColor: `${themeData.secondary} !important`,
      color: `${themeData.headerText} !important`,
      fontWeight: "600 !important",
      fontSize: "11.5px !important",
      border: `1px solid ${themeData.glassBorder} !important`,
    },
    actions: {
      padding: "12px 18px 18px 18px !important",
      gap: 12,
      borderTop: `1px solid ${themeData.glassBorder}`,
      marginTop: "auto",
      flexWrap: "wrap",
      "@media (max-width:600px)": {
        padding: "10px 14px 14px 14px !important",
      },
    },
    projectLink: {
      display: "inline-flex !important",
      alignItems: "center",
      gap: 6,
      color: `${themeData.headerText} !important`,
      fontWeight: "700 !important",
      fontSize: "13px !important",
      transition: "all 200ms ease",
      padding: "6px 10px",
      borderRadius: 6,
      "&:hover": {
        color: `${themeData.accent} !important`,
        backgroundColor: themeData.secondary,
      },
    },
  }));

export default useStyles;
