import { makeStyles } from "@mui/styles";

const useStyles = (themeData) =>
  makeStyles(() => ({
    container: {
      padding: "100px 24px 80px",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      position: "relative",
      overflow: "hidden",
      width: "100%",
      maxWidth: "100%",
      "&::before": {
        content: '""',
        position: "absolute",
        top: "-140px",
        right: "-60px",
        width: 460,
        height: 460,
        borderRadius: "50%",
        background: themeData.heroGlow1,
        filter: "blur(110px)",
        zIndex: 0,
        pointerEvents: "none",
        animation: "auroraDrift1 18s ease-in-out infinite",
      },
      "&::after": {
        content: '""',
        position: "absolute",
        bottom: "-160px",
        left: "-90px",
        width: 420,
        height: 420,
        borderRadius: "50%",
        background: themeData.heroGlow2,
        filter: "blur(110px)",
        zIndex: 0,
        pointerEvents: "none",
        animation: "auroraDrift2 22s ease-in-out infinite",
      },
    },
    auroraBlob3: {
      position: "absolute",
      top: "20%",
      left: "38%",
      width: 340,
      height: 340,
      borderRadius: "50%",
      background: themeData.heroGlow3,
      filter: "blur(120px)",
      zIndex: 0,
      pointerEvents: "none",
      animation: "auroraDrift3 26s ease-in-out infinite",
    },
    nameGradient: {
      background: themeData.gradient,
      WebkitBackgroundClip: "text",
      backgroundClip: "text",
      WebkitTextFillColor: "transparent",
      color: "transparent",
    },
    section: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      gap: "40px",
      position: "relative",
      zIndex: 1,
      maxWidth: "1200px",
      width: "100%",
      margin: "0 auto",
      "@media (max-width:960px)": {
        flexDirection: "column-reverse",
        textAlign: "center",
        gap: "32px",
      },
    },
    contentLeft: {
      flex: "1 1 580px",
      maxWidth: "680px",
      "@media (max-width:960px)": {
        maxWidth: "100%",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
      },
    },
    mainHeading: {
      fontSize: "clamp(32px, 5vw, 54px) !important",
      fontWeight: "700 !important",
      lineHeight: "1.15 !important",
      marginTop: "8px !important",
    },
    typeWriterWrapper: {
      minHeight: "44px",
      display: "flex",
      alignItems: "center",
      margin: "12px 0px 16px",
      "@media (max-width:960px)": {
        justifyContent: "center",
      },
    },
    borderWrapper: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      position: "relative",
      padding: 6,
      borderRadius: "50%",
      zIndex: 1,
      background: themeData.gradient,
      animation: "$breathe 4s ease-in-out infinite",
      flexShrink: 0,
    },
    "@keyframes breathe": {
      "0%, 100%": {
        boxShadow: `0 0 22px 2px ${themeData.glow}`,
      },
      "50%": {
        boxShadow: `0 0 46px 10px ${themeData.glow}`,
      },
    },
    img: {
      borderRadius: "50%",
      width: "clamp(220px, 24vw, 320px) !important",
      height: "clamp(220px, 24vw, 320px) !important",
      display: "block",
      backgroundColor: themeData.surface,
      boxShadow: `inset 0 0 0 4px ${themeData.background}`,
      "& img": {
        objectFit: "cover",
      },
    },
    ctaContainer: {
      display: "flex",
      flexWrap: "wrap",
      gap: 15,
      marginTop: 25,
      "@media (max-width:960px)": {
        justifyContent: "center",
      },
    },
    ctaOutline: {
      color: `${themeData.text} !important`,
      backgroundColor: `${themeData.transparent} !important`,
      border: `1.5px solid ${themeData.accent} !important`,
      "&:hover": {
        color: `${themeData.background} !important`,
        backgroundColor: `${themeData.accent} !important`,
        boxShadow: `0 0 18px -2px ${themeData.glow} !important`,
      },
    },
    socialMain: {
      margin: "24px 0px 16px",
      "@media (max-width:960px)": {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
      },
    },
    socialContainer: {
      display: "flex",
      gap: 16,
      marginTop: 8,
      "@media (max-width:960px)": {
        justifyContent: "center",
        flexWrap: "wrap",
      },
    },
    iconButton: {
      display: "flex !important",
      alignItems: "center !important",
      height: 40,
      width: 40,
      borderRadius: "50px",
      color: `${themeData.white} !important`,
      fontWeight: 700,
      backgroundColor: themeData.primary,
      transition: "all 0.4s ease-out !important",
      boxShadow: themeData.chipShadow,
      overflow: "hidden",
      "&:hover": {
        width: "140px !important",
        "& $socialText": {
          display: "block !important",
        },
      },
      "@media (hover: none)": {
        "&:hover": {
          width: "40px !important",
          "& $socialText": {
            display: "none",
          },
        },
      },
    },
    socialIcon: {
      transition: "linear 0.4s !important",
      margin: "0 10px",
      borderRadius: 50,
      height: "20px !important",
      width: "20px !important",
      color: themeData.white,
      flexShrink: 0,
    },
    socialText: {
      display: "none !important",
      color: `${themeData.white} !important`,
      whiteSpace: "nowrap",
      fontSize: "13px !important",
      paddingRight: "10px",
    },
    subText: {
      margin: "12px 0px",
      maxWidth: "600px",
      lineHeight: "1.6",
      "& .MuiTypography-root": {
        lineHeight: "1.6 !important",
      },
    },
    workContainer: {
      display: "flex",
      alignItems: "center",
      gap: 20,
      marginTop: 28,
      "@media (max-width:960px)": {
        justifyContent: "center",
      },
    },
    card: {
      padding: "16px 26px",
      borderRadius: 16,
      backgroundColor: themeData.glassBg,
      backdropFilter: "blur(12px)",
      WebkitBackdropFilter: "blur(12px)",
      border: `1px solid ${themeData.glassBorder}`,
      boxShadow: themeData.shadow,
      transition: "transform 250ms ease, box-shadow 250ms ease",
      "& .MuiTypography-head": {
        background: themeData.gradient,
        WebkitBackgroundClip: "text",
        backgroundClip: "text",
        WebkitTextFillColor: "transparent",
      },
      "&:hover": {
        transform: "translateY(-4px)",
        boxShadow: `0px 16px 30px -12px ${themeData.glow}`,
      },
    },
  }));

export default useStyles;
